import { MasterBackupObject } from '../types';

const BACKUP_VERSION = '1.0';

/**
 * Exports the application state to a JSON file downloaded by the browser.
 */
export const exportAppState = (data: Partial<MasterBackupObject>) => {
  const backup: MasterBackupObject = {
    version: BACKUP_VERSION,
    timestamp: new Date().toISOString(),
    config: {
      apiKey: data.config?.apiKey || '',
      youtubeApiKey: data.config?.youtubeApiKey || ''
    },
    lastAnalysis: data.lastAnalysis || null,
    meta: {
      appVersion: 'NicheSensei-v1'
    }
  };

  try {
    const jsonString = JSON.stringify(backup, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    // Format: NicheSensei_Backup_2023-10-27.json
    link.download = `NicheSensei_Backup_${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    return true;
  } catch (error) {
    console.error("Export failed:", error);
    return false;
  }
};

/**
 * Imports application state from a user-provided JSON file.
 * Returns a Promise that resolves with the parsed backup object or rejects with an error.
 */
export const importAppState = (file: File): Promise<MasterBackupObject> => {
  return new Promise((resolve, reject) => {
    if (!file) {
      reject(new Error("No file selected"));
      return;
    }

    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        const data = JSON.parse(text) as MasterBackupObject;
        
        // Integrity Check
        if (!data.version) {
          throw new Error("Invalid backup file: Missing version information.");
        }
        
        if (!data.config) {
          throw new Error("Invalid backup file: Missing configuration data.");
        }

        resolve(data);
      } catch (err) {
        console.error("Import parsing failed:", err);
        reject(new Error("Failed to parse backup file. Please ensure it is a valid JSON file generated by NicheSensei."));
      }
    };
    
    reader.onerror = () => {
      reject(new Error("Failed to read file from disk."));
    };

    reader.readAsText(file);
  });
};
